//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphQL.StarWars.Api.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Descriptions {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Descriptions() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GraphQL.StarWars.Api.Properties.Descriptions", typeof(Descriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string The_id_of_the_0 {
            get {
                return ResourceManager.GetString("The_id_of_the_0", resourceCulture);
            }
        }
        
        internal static string The_name_of_the_0 {
            get {
                return ResourceManager.GetString("The_name_of_the_0", resourceCulture);
            }
        }
        
        internal static string Which_movie_they_appear_in {
            get {
                return ResourceManager.GetString("Which_movie_they_appear_in", resourceCulture);
            }
        }
        
        internal static string A_mechanical_creature_in_the_Star_Wars_universe {
            get {
                return ResourceManager.GetString("A_mechanical_creature_in_the_Star_Wars_universe", resourceCulture);
            }
        }
        
        internal static string The_primary_function_of_the_droid {
            get {
                return ResourceManager.GetString("The_primary_function_of_the_droid", resourceCulture);
            }
        }
        
        internal static string Released_in_0 {
            get {
                return ResourceManager.GetString("Released_in_0", resourceCulture);
            }
        }
        
        internal static string One_of_the_films_in_the_Star_Wars_Trilogy {
            get {
                return ResourceManager.GetString("One_of_the_films_in_the_Star_Wars_Trilogy", resourceCulture);
            }
        }
        
        internal static string The_home_planet_of_the_human {
            get {
                return ResourceManager.GetString("The_home_planet_of_the_human", resourceCulture);
            }
        }
    }
}
