// <auto-generated />
using System;
using GraphQL.StarWars.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GraphQL.StarWars.Repositories.Migrations
{
    [DbContext(typeof(StarWarsContext))]
    partial class StarWarsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("GraphQL.StarWars.Repositories.Models.Character", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Character");
                });

            modelBuilder.Entity("GraphQL.StarWars.Repositories.Models.CharacterEpisode", b =>
                {
                    b.Property<int>("CharacterId");

                    b.Property<int>("EpisodeId");

                    b.HasKey("CharacterId", "EpisodeId");

                    b.HasIndex("EpisodeId");

                    b.ToTable("CharacterEpisodes");
                });

            modelBuilder.Entity("GraphQL.StarWars.Repositories.Models.CharacterFriend", b =>
                {
                    b.Property<int>("CharacterId");

                    b.Property<int>("FriendId");

                    b.HasKey("CharacterId", "FriendId");

                    b.HasIndex("FriendId");

                    b.ToTable("CharacterFriends");
                });

            modelBuilder.Entity("GraphQL.StarWars.Repositories.Models.Episode", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int?>("HeroId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("GraphQL.StarWars.Repositories.Models.Planet", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("GraphQL.StarWars.Repositories.Models.Droid", b =>
                {
                    b.HasBaseType("GraphQL.StarWars.Repositories.Models.Character");

                    b.Property<string>("PrimaryFunction");

                    b.HasDiscriminator().HasValue("Droid");
                });

            modelBuilder.Entity("GraphQL.StarWars.Repositories.Models.Human", b =>
                {
                    b.HasBaseType("GraphQL.StarWars.Repositories.Models.Character");

                    b.Property<int?>("HomePlanetId");

                    b.HasIndex("HomePlanetId");

                    b.HasDiscriminator().HasValue("Human");
                });

            modelBuilder.Entity("GraphQL.StarWars.Repositories.Models.CharacterEpisode", b =>
                {
                    b.HasOne("GraphQL.StarWars.Repositories.Models.Character", "Character")
                        .WithMany("CharacterEpisodes")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GraphQL.StarWars.Repositories.Models.Episode", "Episode")
                        .WithMany("CharacterEpisodes")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GraphQL.StarWars.Repositories.Models.CharacterFriend", b =>
                {
                    b.HasOne("GraphQL.StarWars.Repositories.Models.Character", "Character")
                        .WithMany("CharacterFriends")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GraphQL.StarWars.Repositories.Models.Character", "Friend")
                        .WithMany("FriendCharacters")
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GraphQL.StarWars.Repositories.Models.Episode", b =>
                {
                    b.HasOne("GraphQL.StarWars.Repositories.Models.Character", "Hero")
                        .WithMany()
                        .HasForeignKey("HeroId");
                });

            modelBuilder.Entity("GraphQL.StarWars.Repositories.Models.Human", b =>
                {
                    b.HasOne("GraphQL.StarWars.Repositories.Models.Planet", "HomePlanet")
                        .WithMany("Humans")
                        .HasForeignKey("HomePlanetId");
                });
#pragma warning restore 612, 618
        }
    }
}
